# 1. slicing/stacking arrays, indexing with boolean arrays - numpy

In [3]:
import numpy as np
a = np.arange(10).reshape(2,5)
print(a)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [10]:
print(a.shape)
# print indivial -particular element by index row,column
print(a[0,0])
print(a[0,4])
print(a[1,0])
print(a[1,4])

(2, 5)
0
4
5
9


In [16]:
# print particular row -0 
print(a[:1,])

[[0 1 2 3 4]]


In [18]:
# print particular row -1
print(a[1:2,])

[[5 6 7 8 9]]


In [19]:
# print row 0 to 1
print(a[0:2,])

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [20]:
# print columns 0
print(a[:, 0:1])

[[0]
 [5]]


In [21]:
# print columns 2
print(a[:, 1:2])

[[1]
 [6]]


In [22]:
# print columns 3
print(a[:, 2:3])

[[2]
 [7]]


In [25]:
# print columns last column
print(a[:, -1:])

[[4]
 [9]]


In [26]:
#print 2 to 3 cloumns -both included
print(a[:, 2:4])

[[2 3]
 [7 8]]


In [27]:
# print first row and last two columns
print(a[:1,-2:])

[[3 4]]


In [28]:
# print second row and last two columns
print(a[1:2,-2:])

[[8 9]]


In [29]:
a= np.arange(0,10).reshape(2,5)
print(a)
b=np.arange(10,20).reshape(2,5)
print(b)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[10 11 12 13 14]
 [15 16 17 18 19]]


In [31]:
c=np.vstack( (a,b) )
print(c)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [32]:
c=np.hstack( (a,b) )
print(c)

[[ 0  1  2  3  4 10 11 12 13 14]
 [ 5  6  7  8  9 15 16 17 18 19]]


In [33]:
 d = c > 5
print(d)

[[False False False False False  True  True  True  True  True]
 [False  True  True  True  True  True  True  True  True  True]]
