## **A data analyst may be responsible for a variety of tasks, including cleaning and preparing datasets, analyzing data trends and patterns, developing predictive models, and communicating insights to stakeholders.**

# Business Problem

1. Given Iris Dataset -  Classify Flower Types, based on features provided

# Task Objective - Using Numpy & Pandas - Find Data Insights
1. Leverage Data Analytics to discern patterns in the Iris dataset, enabling precise classification of flower types through insightful exploration and interpretation of feature relationships.




## Import Python Modules

In [43]:
# Load necessary pyhton modules
import numpy as np
import pandas as pd


## Load IRIS Dataset

In [44]:
iris = pd.read_csv("dataset\IRIS.csv")

## Basic Inspection on dataset

In [45]:
def basic_inspection(table):
    print("Top 5 Records of dataset")
    print(table.head())
    print()
        
    print("Bottom Records of dataset")
    print(table.tail())
    print()
    
    print("Column/features/Variable  - Names of Given dataset")
    print(table.columns)
    print()
    
    print("Shape(rows x columns) - of Given dataset")
    print(table.shape)
    print()
    
    print("Data types - Given Column Names")
    print(table.dtypes)
    print()
    
    print("Summry of dataset")
    print(table.info())
    print()
    
    print("To see the count of null/nan values in columns of dataset")
    print(table.isnull().value_counts())
    print()
    
    print("Dataset Summary ")
    print(table.describe())
    print()
    
basic_inspection(iris)

Top 5 Records of dataset
   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

Bottom Records of dataset
     sepal_length  sepal_width  petal_length  petal_width    species
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

Column/features/Variable  - Names of Given dataset
Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtyp

## Data Insights

1. Given dataset (Iris) - Records of 150  with 5  features/Variables
2. Independent features /Varaibles - sepal_length, sepal_width, petal_length, petal_width and  ouput/dependent feature -species
3. Given dataset - There are no missing values in all the columns
4. Given dataset - Independent features data types are float/Real numbers and Output varible Categorical Variable
5. sepal_length,  sepal_width , petal_length, petal_width (min: 25% mean, 50% , 75% , max , std)  -- spread is more in petal_length  , Range is more in petal_length  
6. lowest mean/median observed in petal_width
7.  petal_width  (25% -75%) range (0.3 to 1.8) cm - with median 1.3
8.  petal_length (25% -75%) range (1.6 to 5.1) cm - with median 4.3
9.  sepal_width  (25% -75%) range (2.8 to 3.3) cm - with median 3.0
10. sepal_length (25% -75%) range (5.1 to 6.4) cm - with median 5.8

In [46]:
# categorical varialbes
print(iris["species"].value_counts())

species
setosa        50
versicolor    50
virginica     50
Name: count, dtype: int64


In [47]:
#identify duplicate rows
duplicateRows = iris[iris.duplicated()]

#view duplicate rows
duplicateRows

sepal_length  sepal_width  petal_length  petal_width    species
34            4.9          3.1           1.5          0.1     setosa
37            4.9          3.1           1.5          0.1     setosa
142           5.8          2.7           5.1          1.9  virginica

## Grouping by Species - Find the Data Insights

In [48]:
g = iris.groupby("species")
g

In [49]:
g.max()

sepal_length  sepal_width  petal_length  petal_width
species                                                         
setosa               5.8          4.4           1.9          0.6
versicolor           7.0          3.4           5.1          1.8
virginica            7.9          3.8           6.9          2.5

In [50]:
g.min()

sepal_length  sepal_width  petal_length  petal_width
species                                                         
setosa               4.3          2.3           1.0          0.1
versicolor           4.9          2.0           3.0          1.0
virginica            4.9          2.2           4.5          1.4

In [51]:
g[["petal_length","petal_width"]].describe()

petal_length                                               \
                  count   mean       std  min  25%   50%    75%  max   
species                                                                
setosa             50.0  1.464  0.173511  1.0  1.4  1.50  1.575  1.9   
versicolor         50.0  4.260  0.469911  3.0  4.0  4.35  4.600  5.1   
virginica          50.0  5.552  0.551895  4.5  5.1  5.55  5.875  6.9   

           petal_width                                            
                 count   mean       std  min  25%  50%  75%  max  
species                                                           
setosa            50.0  0.244  0.107210  0.1  0.2  0.2  0.3  0.6  
versicolor        50.0  1.326  0.197753  1.0  1.2  1.3  1.5  1.8  
virginica         50.0  2.026  0.274650  1.4  1.8  2.0  2.3  2.5

In [52]:
g.count()

sepal_length  sepal_width  petal_length  petal_width
species                                                         
setosa                50           50            50           50
versicolor            50           50            50           50
virginica             50           50            50           50

$Observations$

-  we can use Petal length & petal width to clasify the flowers
- Setosa min-max (Petal width)(0.1 to 0.6) and Versicolor min-max Petal width(1.0 - 1.8) and Virginica Min-Max(Petal width) (1.4 - 2.5)  - So Versicolor and Virginica - there is 25% overalp and 100% accuracy in Setosa.
- Setosa min-max (Petal length)(1.0 to 1.9) and Versicolor min-max Petal length(3.0 - 5.1) and Virginica Min-Max(Petal length) (4.5- 6.9)  - So Versicolor and Virginica - there is 25% overalp and 100% accuracy in Setosa.

In [53]:
g[["sepal_length","sepal_width"]].describe()

sepal_length                                              \
                  count   mean       std  min    25%  50%  75%  max   
species                                                               
setosa             50.0  5.006  0.352490  4.3  4.800  5.0  5.2  5.8   
versicolor         50.0  5.936  0.516171  4.9  5.600  5.9  6.3  7.0   
virginica          50.0  6.588  0.635880  4.9  6.225  6.5  6.9  7.9   

           sepal_width                                                
                 count   mean       std  min    25%  50%    75%  max  
species                                                               
setosa            50.0  3.418  0.381024  2.3  3.125  3.4  3.675  4.4  
versicolor        50.0  2.770  0.313798  2.0  2.525  2.8  3.000  3.4  
virginica         50.0  2.974  0.322497  2.2  2.800  3.0  3.175  3.8

## Understandign the Overlaping Region -
## versicolor & virginica Based on Petal Width -
## [1.4 to 1.8] both Values are  included

### Petal Width - Histogram - Between 1.4 to 1.8

In [54]:
petal_width_column = iris['petal_width'].to_numpy()

In [55]:
petal_width_column

array([0.2, 0.2, 0.2, 0.2, 0.2, 0.4, 0.3, 0.2, 0.2, 0.1, 0.2, 0.2, 0.1,
       0.1, 0.2, 0.4, 0.4, 0.3, 0.3, 0.3, 0.2, 0.4, 0.2, 0.5, 0.2, 0.2,
       0.4, 0.2, 0.2, 0.2, 0.2, 0.4, 0.1, 0.2, 0.1, 0.2, 0.2, 0.1, 0.2,
       0.2, 0.3, 0.3, 0.2, 0.6, 0.4, 0.3, 0.2, 0.2, 0.2, 0.2, 1.4, 1.5,
       1.5, 1.3, 1.5, 1.3, 1.6, 1. , 1.3, 1.4, 1. , 1.5, 1. , 1.4, 1.3,
       1.4, 1.5, 1. , 1.5, 1.1, 1.8, 1.3, 1.5, 1.2, 1.3, 1.4, 1.4, 1.7,
       1.5, 1. , 1.1, 1. , 1.2, 1.6, 1.5, 1.6, 1.5, 1.3, 1.3, 1.3, 1.2,
       1.4, 1.2, 1. , 1.3, 1.2, 1.3, 1.3, 1.1, 1.3, 2.5, 1.9, 2.1, 1.8,
       2.2, 2.1, 1.7, 1.8, 1.8, 2.5, 2. , 1.9, 2.1, 2. , 2.4, 2.3, 1.8,
       2.2, 2.3, 1.5, 2.3, 2. , 2. , 1.8, 2.1, 1.8, 1.8, 1.8, 2.1, 1.6,
       1.9, 2. , 2.2, 1.5, 1.4, 2.3, 2.4, 1.8, 1.8, 2.1, 2.4, 2.3, 1.9,
       2.3, 2.5, 2.3, 1.9, 2. , 2.3, 1.8])

In [56]:
filter_list = petal_width_column[(petal_width_column >=1.4) & (petal_width_column <=1.8) ]

In [57]:
filter_list

array([1.4, 1.5, 1.5, 1.5, 1.6, 1.4, 1.5, 1.4, 1.4, 1.5, 1.5, 1.8, 1.5,
       1.4, 1.4, 1.7, 1.5, 1.6, 1.5, 1.6, 1.5, 1.4, 1.8, 1.7, 1.8, 1.8,
       1.8, 1.5, 1.8, 1.8, 1.8, 1.8, 1.6, 1.5, 1.4, 1.8, 1.8, 1.8])

In [58]:
np.histogram(filter_list, bins=[1.4,1.5,1.6,1.7,1.8])

(array([ 8, 12,  4, 14], dtype=int64), array([1.4, 1.5, 1.6, 1.7, 1.8]))

 ### Versicolor - Petal Width - Histogram - Between -1.4 to 1.8

In [59]:
versicolr_petal_width = g.get_group('versicolor')["petal_width"]

In [60]:
versicolr_petal_width_column = versicolr_petal_width.to_numpy()

In [61]:
versicolr_petal_width_column

array([1.4, 1.5, 1.5, 1.3, 1.5, 1.3, 1.6, 1. , 1.3, 1.4, 1. , 1.5, 1. ,
       1.4, 1.3, 1.4, 1.5, 1. , 1.5, 1.1, 1.8, 1.3, 1.5, 1.2, 1.3, 1.4,
       1.4, 1.7, 1.5, 1. , 1.1, 1. , 1.2, 1.6, 1.5, 1.6, 1.5, 1.3, 1.3,
       1.3, 1.2, 1.4, 1.2, 1. , 1.3, 1.2, 1.3, 1.3, 1.1, 1.3])

In [62]:
versicolr_petal_width_filter_list = versicolr_petal_width_column[(versicolr_petal_width_column >=1.4) & (versicolr_petal_width_column <=1.8) ]

In [63]:
np.histogram(versicolr_petal_width_filter_list, bins=[1.4,1.5,1.6,1.7,1.8])

(array([ 7, 10,  3,  2], dtype=int64), array([1.4, 1.5, 1.6, 1.7, 1.8]))

 ### virginica - Petal Width - Histogram - Between -1.4 to 1.8

In [64]:
virginica_petal_width = g.get_group('virginica')["petal_width"]

In [65]:
virginica_petal_width_column = virginica_petal_width.to_numpy()

In [66]:
virginica_petal_width_column

array([2.5, 1.9, 2.1, 1.8, 2.2, 2.1, 1.7, 1.8, 1.8, 2.5, 2. , 1.9, 2.1,
       2. , 2.4, 2.3, 1.8, 2.2, 2.3, 1.5, 2.3, 2. , 2. , 1.8, 2.1, 1.8,
       1.8, 1.8, 2.1, 1.6, 1.9, 2. , 2.2, 1.5, 1.4, 2.3, 2.4, 1.8, 1.8,
       2.1, 2.4, 2.3, 1.9, 2.3, 2.5, 2.3, 1.9, 2. , 2.3, 1.8])

In [67]:
virginica_petal_width_filter_list = virginica_petal_width_column[(virginica_petal_width_column >=1.4) & (virginica_petal_width_column <=1.8) ]

In [68]:
np.histogram(virginica_petal_width_filter_list, bins=[1.4,1.5,1.6,1.7,1.8])

(array([ 1,  2,  1, 12], dtype=int64), array([1.4, 1.5, 1.6, 1.7, 1.8]))

$Observations$

-   We can Split versicolor and virginica on Petal Width at 1.6 
-   Petal width less than  1.6 - we can clasify versicolor
-   Petal width greather than equal 1.6 - we can clasify as virginica
-   So, we can increase the accuray from 75% to  94% and overall Iris dataset is 97%

## Conclusions
-  We can use Petal length & petal width to clasify the flowers
-  By using the Petal Width - We can Classify the flower types with 97% Accurate