# Matrix operationa using numpy

In [4]:
import numpy as np
def matrix_add(a,b):
    """Matrix addition is the operation of adding two matrices of the same size to produce a new matrix. 
    The resulting matrix has the same dimensions as the original matrices."""
    if (a.shape == b.shape):
        c = a+b
        return c
    else:
        print(f"Invalid Dimentions of matrices {a.shape} and {b.shape}\n")
        return None

def matrix_sub(a,b):
    """Matrix subtraction is the process of subtracting one matrix from another. 
    This operation can be performed element-wise"""
    if (a.shape == b.shape):
        c=a-b
        return c
    else:
        print(f"Invalid Dimentions of matrices{a.shape} and {b.shape}\n")
        return None


def matrix_mul(a,b):
    """Matrix multiplication refers to the operation of combining 
    two or more matrices into a single result, called a product,"""
    if a.shape[-1] == b.shape[0] :
        c=np.dot(a,b)
        return c
    else:
        print(f"Invalid Dimentions of matrices{a.shape} and {b.shape}\n")
        return None

def matrix_inv(a):
    """The existence of an inverse matrix is guaranteed only 
    if A is non-singular, i.e., det(A) ≠ 0. """
    if np.linalg.det(a) != 0:
        r=np.linalg.inv(a)
        return r
    else:
        print("Det of matrix is zero\n")
        return None


def matrix_transpose(a):
    """Matrix transpose is an operation that are used in linear algebra and mathematics
    in which the rows and columns of a matrix are switched."""
    return a.transpose()

def matrix_det(a):
    """A matrix determinant is a scalar value that measures the degree of
    linear independence of the rows or columns of a square matrix. 
    It is calculated using a specific formula based on the entries of the matrix. 
    The determinant has important properties in linear algebra, such as being zero 
    if and only if the matrix is singular"""
    
    if a.shape[0] == a.shape[1]:
        return np.linalg.det(a)
    else:
        print(f"Invalid Matrix shape {a.shape}\n")
        return None

def matrix_solve_equation(a,b):
    """solve linear equations"""
    if True:
        return np.linalg.solve(a, b)
    else:
        print("Invalid Matrix dimensions\n")
        return None

def eigen_vectors_values(a):
    """find eigen vectors and eigen values"""
    if a.shape[0] == a.shape[1]:
        eigenvalues, eigenvectors = np.linalg.eig(a)
        return eigenvalues,eigenvectors
    else:
        print("Invalid Matrix dimensions\n")
        return None

In [13]:
a = np.zeros((3,3))
print("matrix a\n ",a)
print("\n")

b = np.ones((3,3))
print("matrix b \n",b)
print("\n")

c=matrix_add(a,b)
print("Matrix Addition :\n",c)
print("\n")

d=matrix_sub(a,b)
print("Matrix Subtration:\n",d)

print("\n")
a = np.array([[1,2],[2,3],[3,4]])
print("matrix a\n ",a)
print("\n")

b = np.array([[1,0],[0,1]])
print("matrix b\n ",b)
print("\n")

c=matrix_mul(a,b)
print("matrix multiplication output:\n")
print(c)
print("\n")


m = np.array([[1,2],[3,4]])
print("Original matrix:")
print(m)
print("\n")

result=matrix_inv(m)
print("Inverse of the said matrix:")
print(result)
print("\n")

d = np.array([[1,2], [3,4],[5,6]])
print("Original matrix:")
print(d)
print(d.shape)
print(""\n")
f= matrix_transpose(d)
print("matrix transpose\n")
print(f)
print("\n")

# Solve the system of linear equations: 2x + 3y = 8, 4x - 2y = 6.
coefficients = np.array([[2, 3], [4, -2]])
constants = np.array([8, 6])
result = matrix_solve_equation(coefficients,constants)
print("Solution:\n", result)
print("\n")



D = np.array([[1, 2], [2, 4]])
eigenvalues, eigenvectors = eigen_vectors_values(D)
print("Eigenvalues:\n", eigenvalues)
print("\n")
print("Eigenvectors:\n", eigenvectors)


matrix a
  [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


matrix b 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


Matrix Addition :
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


Matrix Subtration:
 [[-1. -1. -1.]
 [-1. -1. -1.]
 [-1. -1. -1.]]


matrix a
  [[1 2]
 [2 3]
 [3 4]]


matrix b
  [[1 0]
 [0 1]]


matrix multiplication output:

[[1 2]
 [2 3]
 [3 4]]


Original matrix:
[[1 2]
 [3 4]]


Inverse of the said matrix:
[[-2.   1. ]
 [ 1.5 -0.5]]


[[1 2]
 [3 4]
 [5 6]]
(3, 2)
matrix transpose

[[1 3 5]
 [2 4 6]]


Solution:
 [2.125 1.25 ]


Eigenvalues:
 [0. 5.]


Eigenvectors:
 [[-0.89442719 -0.4472136 ]
 [ 0.4472136  -0.89442719]]
